services:
    random_redirector:
        container_name: "random_redirector"
        image: "ghcr.io/9-fs/random_redirector:2.3.0"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        volumes:
            - "/mnt/user/appdata/random_redirector/assets/:/app/assets/:rw"
            - "/mnt/user/appdata/random_redirector/config/:/app/config/:rw"
            - "/mnt/user/appdata/random_redirector/log/:/app/log/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "6900:6900"
        deploy:
            resources:
                limits:
                    memory: "1G"