services:
    random_asset_displayer:
        container_name: "random_asset_displayer"
        image: "ghcr.io/9-fs/random_asset_displayer:3.0.0"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        volumes:
            - "/mnt/user/appdata/random_asset_displayer/assets/:/app/assets/:rw"
            - "/mnt/user/appdata/random_asset_displayer/config/:/app/config/:rw"
            - "/mnt/user/appdata/random_asset_displayer/log/:/app/log/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "6900:6900"
        deploy:
            resources:
                limits:
                    memory: "1G"