version: "3"

services:
    random_redirector:
        container_name: "random_redirector"
        image: "ghcr.io/9-fs/random_redirector:2.2.3"
        environment:
            HOST_OS: "Unraid"
            PGID: 100
            PUID: 99
            TZ: "UTC"
            UMASK: 000
        volumes:
            - "/mnt/user/appdata/random_redirector/config/:/app/config/:rw"
            - "/mnt/user/appdata/random_redirector/log/:/app/log/:rw"
        network_mode: "bridge"
        ports:
            - "6900:6900"
        deploy:
            resources:
                limits:
                    memory: "1G"
        user: "99:100"

networks: {}