name: "random_asset_displayer"

services:
    random_asset_displayer:
        container_name: "random_asset_displayer"
        image: "ghcr.io/9-fs/random_asset_displayer:latest"
        mem_limit: "1G"
        volumes:
            - "/path/to/random_asset_displayer/assets/:/app/assets/"
            - "/path/to/random_asset_displayer/config/:/app/config/"
            - "/path/to/random_asset_displayer/log/:/app/log/"
        ports:
            - "6900:6900"